[package]
name = "runas"
version = "0.1.0"
authors = ["keyboard-slayer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.5"
rpassword = "5.0.1"
pwhash = "1"
libc = "0.2.84"
users = "0.11.0" 
